import { GoalEdition } from '../../core/enums/editions';
import { PCMSLanguage } from '../../core/enums/pcms-language';
import { Portals } from '../../core/enums/portals';
import { SDLLanguage } from '../../core/enums/sdl-language';
import { Locale } from '../locales.config';
import { EditionsConfig } from './types';

export const config: EditionsConfig<Portals.GOAL> = {
  [GoalEdition.AR]: {
    language: Locale.AR,
    pcmsLanguage: PCMSLanguage.ar,
    sdlLanguage: SDLLanguage.AR,
    intlLocale: 'ar',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['ar'],
    withVideoIcon: false,
    seo: {
      name: 'العربية Goal.com',
    },
    localazy: 'ar',
  },
  [GoalEdition.AR_EG]: {
    language: Locale.AR,
    pcmsLanguage: PCMSLanguage.ar,
    sdlLanguage: SDLLanguage.AR,
    intlLocale: 'ar-EG',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['ar-eg'],
    withVideoIcon: false,
    seo: {
      name: 'مصر Goal.com',
    },
    localazy: 'ar',
  },
  [GoalEdition.AR_SA]: {
    language: Locale.AR,
    pcmsLanguage: PCMSLanguage.ar,
    sdlLanguage: SDLLanguage.AR,
    intlLocale: 'ar-SA',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['ar-sa'],
    withVideoIcon: false,
    seo: {
      name: 'السعودية Goal.com',
    },
    localazy: 'ar',
  },
  [GoalEdition.BR]: {
    language: Locale.PT_BR,
    pcmsLanguage: PCMSLanguage.pt_br,
    sdlLanguage: SDLLanguage.PT_BR,
    intlLocale: 'pt-BR',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['pt', 'pt-br'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Brasil',
    },
    localazy: 'pt-BR',
  },
  [GoalEdition.DE]: {
    language: Locale.DE,
    pcmsLanguage: PCMSLanguage.de,
    sdlLanguage: SDLLanguage.DE,
    intlLocale: 'de',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['de'],
    withVideoIcon: true,
    seo: {
      name: 'Goal.com Deutschland',
    },
    localazy: 'de',
  },
  [GoalEdition.EN]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GB',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_AE]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GB',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-ae'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com United Arab Emirates',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_AU]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-AU',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-au', 'en-cc', 'en-nz'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Australia',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_BH]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GB',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-bh'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com English Bahrain',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_CM]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-CM',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-cm'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Cameroon',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_GB]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GB',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['en-gb'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com UK',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_GH]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GH',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-gh'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Ghana',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_IN]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-IN',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['en-bd', 'en-bt', 'en-in', 'en-mv', 'en-np'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com India',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_KE]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-KE',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-ke'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Kenya',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_KW]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GB',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-kw'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com English Kuwait',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_MY]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-MY',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-my'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Malaysia',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_NG]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-NG',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-ng'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Nigeria',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_OM]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-OM',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-om'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com English Oman',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_QA]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GB',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-qa'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com English Qatar',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_SA]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-GB',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-sa'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com English Saudi Arabia',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_SG]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-SG',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-kh', 'en-la', 'en-sg'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Singapore',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_TZA]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-TZ',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-tz'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Tanzania',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_UG]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-UG',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['en-ug'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Uganda',
    },
    localazy: 'en',
  },
  [GoalEdition.EN_US]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-US',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: [
      'en-ag',
      'en-as',
      'en-bs',
      'en-bz',
      'en-dm',
      'en-jm',
      'en-us',
      'en-vi',
    ],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com US',
    },
    localazy: 'en-US',
  },
  [GoalEdition.EN_ZA]: {
    language: Locale.EN,
    pcmsLanguage: PCMSLanguage.en,
    sdlLanguage: SDLLanguage.EN,
    intlLocale: 'en-ZA',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['en-za', 'en-zw'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com South Africa',
    },
    localazy: 'en-ZA',
  },
  [GoalEdition.ES]: {
    language: Locale.ES,
    pcmsLanguage: PCMSLanguage.es,
    sdlLanguage: SDLLanguage.ES,
    intlLocale: 'es',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['es', 'es-ad', 'es-es'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Espana',
    },
    localazy: 'es',
  },
  [GoalEdition.ES_AR]: {
    language: Locale.ES,
    pcmsLanguage: PCMSLanguage.es,
    sdlLanguage: SDLLanguage.ES,
    intlLocale: 'es-AR',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['es-ar', 'es-bo', 'es-ec', 'es-pe', 'es-py', 'es-uy'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Argentina',
    },
    localazy: 'es',
  },
  [GoalEdition.ES_CL]: {
    language: Locale.ES,
    pcmsLanguage: PCMSLanguage.es,
    sdlLanguage: SDLLanguage.ES,
    intlLocale: 'es-CL',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['es-cl'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Chile',
    },
    localazy: 'es',
  },
  [GoalEdition.ES_CO]: {
    language: Locale.ES,
    pcmsLanguage: PCMSLanguage.es,
    sdlLanguage: SDLLanguage.ES,
    intlLocale: 'es-CO',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['es-co', 'es-ve'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Colombia',
    },
    localazy: 'es',
  },
  [GoalEdition.ES_MX]: {
    language: Locale.ES,
    pcmsLanguage: PCMSLanguage.es,
    sdlLanguage: SDLLanguage.ES,
    intlLocale: 'es-MX',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: [
      'es-cr',
      'es-cu',
      'es-do',
      'es-gt',
      'es-hn',
      'es-mx',
      'es-ni',
      'es-pa',
      'es-pr',
      'es-sv',
      'es-us',
    ],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com México',
    },
    localazy: 'es',
  },
  [GoalEdition.FR]: {
    language: Locale.FR,
    pcmsLanguage: PCMSLanguage.fr,
    sdlLanguage: SDLLanguage.FR,
    intlLocale: 'fr',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['fr'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Français',
    },
    localazy: 'fr',
  },
  [GoalEdition.HU]: {
    language: Locale.HU_HU,
    pcmsLanguage: PCMSLanguage.hu,
    sdlLanguage: SDLLanguage.HU_HU,
    intlLocale: 'hu',
    betting: true,
    bettingE2: false,
    betterCollectiveBetting: false,
    hreflangs: ['hu'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Magyarország',
    },
    localazy: 'hu',
  },
  [GoalEdition.ID]: {
    language: Locale.ID_ID,
    pcmsLanguage: PCMSLanguage.id,
    sdlLanguage: SDLLanguage.ID_ID,
    intlLocale: 'id',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['id'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Indonesia',
    },
    localazy: 'id',
  },
  [GoalEdition.IT]: {
    language: Locale.IT,
    pcmsLanguage: PCMSLanguage.it,
    sdlLanguage: SDLLanguage.IT,
    intlLocale: 'it',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: true,
    hreflangs: ['it'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Italia',
    },
    localazy: 'it',
  },
  [GoalEdition.JP]: {
    language: Locale.JA,
    pcmsLanguage: PCMSLanguage.ja,
    sdlLanguage: SDLLanguage.JA,
    intlLocale: 'ja',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['ja'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com 日本',
    },
    localazy: 'ja',
  },
  [GoalEdition.KR]: {
    language: Locale.KO,
    pcmsLanguage: PCMSLanguage.ko,
    sdlLanguage: SDLLanguage.KO,
    intlLocale: 'ko',
    betting: true,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['ko'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com 한국어',
    },
    localazy: 'ko',
  },
  [GoalEdition.TH]: {
    language: Locale.TH_TH,
    pcmsLanguage: PCMSLanguage.th,
    sdlLanguage: SDLLanguage.TH_TH,
    intlLocale: 'th',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['th'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com ภาษาไทย',
    },
    localazy: 'th',
  },
  [GoalEdition.TR]: {
    language: Locale.TR_TR,
    pcmsLanguage: PCMSLanguage.tr,
    sdlLanguage: SDLLanguage.TR_TR,
    intlLocale: 'tr',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['tr'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Türkçe',
    },
    localazy: 'tr',
  },
  [GoalEdition.VN]: {
    language: Locale.VI_VN,
    pcmsLanguage: PCMSLanguage.vi,
    sdlLanguage: SDLLanguage.VI_VN,
    intlLocale: 'vi',
    betting: false,
    bettingE2: true,
    betterCollectiveBetting: false,
    hreflangs: ['vi'],
    withVideoIcon: false,
    seo: {
      name: 'Goal.com Việt Nam',
    },
    localazy: 'vi',
  },
};
