export type Edition = GoalEdition | VZEdition;

export enum GoalEdition {
  AR = 'ar',
  AR_EG = 'ar-eg',
  AR_SA = 'ar-sa',
  BR = 'br',
  DE = 'de',
  EN = 'en',
  EN_AE = 'en-ae',
  EN_AU = 'en-au',
  EN_BH = 'en-bh',
  EN_CM = 'en-cm',
  EN_GB = 'en-gb',
  EN_GH = 'en-gh',
  EN_IN = 'en-in',
  EN_KE = 'en-ke',
  EN_KW = 'en-kw',
  EN_MY = 'en-my',
  EN_NG = 'en-ng',
  EN_OM = 'en-om',
  EN_QA = 'en-qa',
  EN_SA = 'en-sa',
  EN_SG = 'en-sg',
  EN_TZA = 'en-tza',
  EN_UG = 'en-ug',
  EN_US = 'en-us',
  EN_ZA = 'en-za',
  ES = 'es',
  ES_AR = 'es-ar',
  ES_CL = 'es-cl',
  ES_CO = 'es-co',
  ES_MX = 'es-mx',
  FR = 'fr',
  HU = 'hu',
  ID = 'id',
  IT = 'it',
  JP = 'jp',
  KR = 'kr',
  TH = 'th',
  TR = 'tr',
  VN = 'vn',
}

export enum VZEdition {
  NL = 'nl',
}

export enum SpoxEdition {
  DE = 'de',
}

// export const goalEditionNames: Record<GoalEdition, string> = {
//   ar: 'العربية',
//   'ar-eg': 'مصر',
//   'ar-sa': 'السعودية',
//   br: 'Português',
//   de: 'Deutsch',
//   en: 'English',
//   'en-ae': 'United Arab Emirates',
//   'en-au': 'Australia',
//   'en-bh': 'Bahrain',
//   'en-cm': 'Cameroon',
//   'en-gb': 'UK',
//   'en-gh': 'Ghana',
//   'en-in': 'India',
//   'en-ke': 'Kenya',
//   'en-kw': 'Kuwait',
//   'en-my': 'Malaysia',
//   'en-ng': 'Nigeria',
//   'en-om': 'Oman',
//   'en-qa': 'Qatar',
//   'en-sa': 'Saudi Arabia',
//   'en-sg': 'Singapore',
//   'en-tza': 'Tanzania',
//   'en-ug': 'Uganda',
//   'en-us': 'USA',
//   'en-za': 'South Africa',
//   es: 'Español',
//   'es-ar': 'Argentina',
//   'es-cl': 'Chile',
//   'es-co': 'Colombia',
//   'es-mx': 'México',
//   fr: 'Français',
//   hu: 'Magyar',
//   id: 'Indonesia',
//   it: 'Italiano',
//   jp: '日本語',
//   kr: '한국어',
//   th: 'ไทย',
//   tr: 'Türkçe',
//   vn: 'ViệtNam',
// };
