export enum SDLLanguage {
  AR = 'ar',
  DE = 'de',
  EN = 'en',
  ES = 'es',
  FR = 'fr',
  HR_HR = 'hr_HR',
  HU_HU = 'hu_HU',
  ID_ID = 'id_ID',
  IT = 'it',
  JA = 'ja',
  KO = 'ko',
  NL = 'nl',
  PT_BR = 'pt_BR',
  TH_TH = 'th_TH',
  TR_TR = 'tr_TR',
  VI_VN = 'vi_VN',
  ZH_CN = 'zh_CN',
  ZH_TW = 'zh_TW',
}
